### ISSUE TITLE
Distinguish between jakarta.ws.rs.Produces and jakarta.enterprise.inject.Produces

### ISSUE THREAD

**Issue by Mandiiiiiii** [eclipse/lsp4jakarta#139] opened 2021-04-16 10:58 UTC
Diagnostics and quick fixes for `@Produces` in CDI should only work with `@Produces` in `jakarta.enterprise.inject` and ignore `@Produces` in `jakarta.ws.rs`

Related PR:
- https://github.com/eclipse/lsp4jakarta/pull/112
- https://github.com/eclipse/lsp4jakarta/pull/125

**Comment by kathrynkodama** [comment] 2021-04-26 12:57
Closing as it is a duplicate of #140

**Closed by kathrynkodama** 2021-04-26 12:57 UTC
