### ISSUE TITLE
User input left in when snippet is selected

### ISSUE THREAD

**Issue by TrevCraw** [eclipse/lsp4jakarta#353] opened 2022-10-27 20:45 UTC
From the example below, "jaxrc" is left in when the `jaxrc` snippet was selected.
```
jaxrcpackage packagename;
					
					import jakarta.ws.rs.GET;
					import jakarta.ws.rs.Path;
					import jakarta.ws.rs.Produces;
					import jakarta.ws.rs.core.MediaType;
					
					@Path("/path")
					public class classname {
					
						@GET
						@Produces(MediaType.TEXT_PLAIN)
						public String methodname() {
							return "hello";
						}
					}
```
Issue also occurs with `servletwebfilter` snippet. Assumption is that this occurs with all snippets, but investigation is required.

Expected behaviour is that user input to the left of where the snippet is selected would be erased.

(Issue originally reported in https://github.com/eclipse/lsp4jakarta/issues/349 - it will handle the indentation issue only.)

**Comment by dshimo** [comment] 2022-11-10 21:11
Looks resolved in VS Code to me

**Comment by turkeylurkey** [comment] 2022-11-16 19:44
It is resolved in IntelliJ.

**Comment by turkeylurkey** [comment] 2022-11-16 19:45
However, if you type some dots before the string the issue remains:
```
...........jaxrcpackage io.openliberty.sample.system;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
...
```

**Comment by turkeylurkey** [comment] 2022-11-16 19:53
Actually, after trying with different characters I cannot reproduce this anymore. `...........jaxrc`

**Comment by bensonnw** [comment] 2022-11-16 21:00
As the fix has been verified in different editors, closing it.

**Closed by bensonnw** 2022-11-16 21:00 UTC
Labels: bug, must-fix
