### ISSUE TITLE
NPE from Diagnostic.getData()

### ISSUE THREAD

**Issue by dshimo** [eclipse/lsp4jakarta#460] opened 2023-05-31 18:28 UTC
A mouseover the diagnostics and/or its related problems in the problems tab will trigger this output error. 
Here is a text output:
```
[Error - 10:18:55 AM] Request textDocument/codeAction failed.
  Message: Request jakarta/java/codeaction failed with message: java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "org.eclipse.lsp4j.Diagnostic.getData()" is null
  Code: -32603 
```

<img width="790" alt="image" src="https://github.com/eclipse/lsp4jakarta/assets/8934136/ab50f02c-70f5-4bb8-aaab-9d3b52100d7d">

<img width="788" alt="image" src="https://github.com/eclipse/lsp4jakarta/assets/8934136/fec64f52-c606-494a-be6f-30bbabb00a27">

<img width="778" alt="image" src="https://github.com/eclipse/lsp4jakarta/assets/8934136/03924006-cec0-43a6-a38f-8ab27235bbc7">

**Comment by TrevCraw** [comment] 2023-06-01 14:37
Duplicate of https://github.com/eclipse/lsp4jakarta/issues/416

**Closed** 2023-06-01 14:42 UTC
