### ISSUE TITLE
Cannot satisfy dependency error on mvn install

### ISSUE THREAD

**Issue by lamminade** [eclipse/lsp4jakarta#94] opened 2021-02-12 16:31 UTC
Getting an error on my machine when running `mvn clean install` in the jakarta-eclipse folder, 

`[DEBUG] Resolving target definition content...
[DEBUG] No solution found because the problem is unsatisfiable.: [Unable to satisfy dependency from com.google.guava 27.1.0.v20190517-1946 to osgi.ee; (&(osgi.ee=JavaSE)(version=1.7)).; Unable to satisfy dependency from com.ibm.icu 64.2.0.v20190507-1337 to osgi.ee; (&(osgi.ee=JavaSE)(version=1.7)).;

...

[ERROR] Cannot resolve target definition:
[ERROR]   Software being installed: org.eclipse.buildship.feature.group 3.1.4.v20200326-1743
[ERROR]   Missing requirement: com.google.guava 27.1.0.v20190517-1946 requires 'osgi.ee; (&(osgi.ee=JavaSE)(version=1.7))' but it could not be found
[ERROR]   Cannot satisfy dependency: org.eclipse.buildship.core 3.1.4.v20200326-1743 depends on: osgi.bundle; com.google.guava [27.0.0,28.0.0)
[ERROR]   Cannot satisfy dependency: org.eclipse.buildship.feature.group 3.1.4.v20200326-1743 depends on: org.eclipse.equinox.p2.iu; org.eclipse.buildship.core [3.1.4.v20200326-1743,3.1.4.v20200326-1743]
[ERROR] 
[ERROR] Failed to resolve target definition /Users/ldawson/.m2/repository/org/eclipse/jdt/ls/org.eclipse.jdt.ls.tp/0.57.0.20200619102332/org.eclipse.jdt.ls.tp-0.57.0.20200619102332.target: See log for details -> [Help 1]
org.apache.maven.MavenExecutionException: Failed to resolve target definition /Users/ldawson/.m2/repository/org/eclipse/jdt/ls/org.eclipse.jdt.ls.tp/0.57.0.20200619102332/org.eclipse.jdt.ls.tp-0.57.0.20200619102332.target`

Eclipse:

Eclipse IDE for Java Developers (includes Incubating components)
Version: 2020-12 (4.18.0)
Build id: 20201210-1552

Java:

openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.24.0, JRE 11 Mac OS X amd64-64-Bit Compressed References 20210120_897 (JIT enabled, AOT enabled)
OpenJ9   - 345e1b09e
OMR      - 741e94ea8
JCL      - 0a86953833 based on jdk-11.0.10+9)

We tried 
- updating Java version
- deleting the .m2/repository and running `mvn -U clean install`
- uninstalling & reinstalling buildship 
- adding `tycho-snapshots` to the jakarta-eclipse pom.xml
- adding `osgi 3.7.1` to the core pom.xml

**Comment by kathrynkodama** [comment] 2021-09-14 20:24
Closing as I cannot reproduce this. To re-open if it occurs again.

**Closed by kathrynkodama** 2021-09-14 20:24 UTC
Labels: bug
