### ISSUE TITLE
Diagnostic is only reported on save (versus on change)

### ISSUE THREAD

**Issue by yeekangc** [eclipse/lsp4jakarta#351] opened 2022-10-26 08:38 UTC
It appears that diagnostics may not be reported as developers make changes but only upon save.

e.g., changing public method for a Jakarta REST service to a private method.  The diagnostic, "Only public methods may be exposed as resource methods", didn't appear until the class file was saved.

This is contrary to what happened when the reverse was done i.e. changing the private method to a public method.  The diagnostic was cleared right away.

This was observed on Eclipse IDE 2022-09 on Mac with Liberty Tools 0.4 (with Eclipse LSP4Jakarta 0.1).

**Comment by TrevCraw** [comment] 2022-10-27 20:15
@bensonnw and @mattbsox to attempt to reproduce - investigate other diagnostic scenarios to seem if same issue occurs

**Comment by bensonnw** [comment] 2022-11-01 17:19
I can see same issue happens to other annotations. I think it's a regression, didn't see the problem before.

**Comment by mattbsox** [comment] 2022-11-01 18:45
Seeing the same behavior in other scenarios. It's happening when I make a change to create an error and to fix an error.

**Comment by dshimo** [comment] 2022-11-01 19:31
Seeing the same behavior in VS Code

**Comment by turkeylurkey** [comment] 2022-11-01 21:00
I tried it in IntelliJ but it is not an issue there. 

Looking at org.eclipse.lsp4jakarta.JakartaTextDocumentService.triggerValidationFor(List<String>) there is a call 
```
CompletableFuture.supplyAsync(() -> { ... 
}).thenApply(jakartaDiagnostics -> { ...
  return jakartaDiagnostics;
});
```
but don't we need a call to `.get()` to run the code? Similar code in the MicroProfile language server runs in the context `org.eclipse.lsp4mp.ls.java.JavaTextDocuments.JavaTextDocument.executeIfInMicroProfileProject(BiFunction<ProjectLabelInfoEntry, CancelChecker, CompletableFuture<T>>, T)` which may run the code.

**Comment by bensonnw** [comment] 2022-11-16 20:41
The problem is a timing issue. When diagnostic collector is doing the validation, the Java model is out of sync. with the underneath resource, so the Java model doesn't have the latest changes, that's why the diagnostic message remains. I noticed there is piece of code has been removed from JDTUtils class: 
                        long st = System.currentTimeMillis();
                        // Give underlying resource time to catch up
                        // (timeout at COMPILATION_UNIT_UPDATE_TIMEOUT milliseconds).
                        long endTime = System.currentTimeMillis() + COMPILATION_UNIT_UPDATE_TIMEOUT;
                        while (!unit.isConsistent() && System.currentTimeMillis() < endTime) {
                        }
The code is trying to sync the CU with the resource, without it, the CU will not pick up the changes from editor right away.
@kathrynkodama The change is made in the PR to support command handler, any reason for removing it?

**Comment by kathrynkodama** [comment] 2022-11-16 20:54
@bensonnw It was removed to sync with the same class in JDT LS: https://github.com/eclipse/eclipse.jdt.ls/blob/master/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java. Makes sense to add back in if it's the cause of the Java model out of sync. How does JDT LS handle?

**Comment by dshimo** [comment] 2022-11-21 22:31
Seems resolved in VS Code

**Comment by bensonnw** [comment] 2022-11-22 17:45
Closing it as changes are in place

**Closed by bensonnw** 2022-11-22 17:45 UTC
Labels: bug, must-fix
